// Виджеты с графиками
export { default as PortfolioChartWidget } from './PortfolioChartWidget.vue'
export { default as PortfolioProfitChartWidget } from './PortfolioProfitChartWidget.vue'
export { default as PortfolioValueChartWidget } from './PortfolioValueChartWidget.vue'
export { default as PayoutsChartWidget } from './PayoutsChartWidget.vue'
export { default as PayoutsByAssetChartWidget } from './PayoutsByAssetChartWidget.vue'
export { default as AssetReturnsChartWidget } from './AssetReturnsChartWidget.vue'
export { default as MonthlyFlowChartWidget } from './MonthlyFlowChartWidget.vue'
export { default as OperationsBreakdownChartWidget } from './OperationsBreakdownChartWidget.vue'
export { default as AnalyticsAssetDistributionWidget } from './AnalyticsAssetDistributionWidget.vue'
export { default as PortfoliosDistributionChartWidget } from './PortfoliosDistributionChartWidget.vue'
export { default as AssetAllocationWidget } from './AssetAllocationWidget.vue'
